import { EditorThemeClasses } from 'lexical'

export const editorTheme: EditorThemeClasses = {
  ltr: 'text-left',
  rtl: 'text-right',
  heading: {
    h1: 'scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl',
    h2: 'scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0',
    h3: 'scroll-m-20 text-2xl font-semibold tracking-tight',
    h4: 'scroll-m-20 text-xl font-semibold tracking-tight',
    h5: 'scroll-m-20 text-lg font-semibold tracking-tight',
    h6: 'scroll-m-20 text-base font-semibold tracking-tight',
  },
  paragraph: 'leading-7 [&:not(:first-child)]:mt-6',
  quote: 'mt-6 border-l-2 pl-6 italic',
  link: 'text-content-presentation-action-link-primary hover:underline hover:cursor-pointer',
  list: {
    checklist: 'relative',
    listitem: 'mx-8',
    listitemChecked:
      'relative mx-2 px-6 list-none outline-none line-through before:content-[""] before:w-4 before:h-4 before:top-0.5 before:left-0 before:cursor-pointer before:block before:bg-cover before:absolute before:border before:border-border-presentation-action-primary before:rounded before:bg-background-presentation-action-primary before:bg-no-repeat after:content-[""] after:cursor-pointer after:border-white after:border-solid after:absolute after:block after:top-[6px] after:w-[3px] after:left-[7px] after:right-[7px] after:h-[6px] after:rotate-45 after:border-r-2 after:border-b-2 after:border-l-0 after:border-t-0',
    listitemUnchecked:
      'relative mx-2 px-6 list-none outline-none before:content-[""] before:w-4 before:h-4 before:top-0.5 before:left-0 before:cursor-pointer before:block before:bg-cover before:absolute before:border before:border-border-presentation-action-primary before:rounded',
    nested: {
      listitem: 'list-none before:hidden after:hidden',
    },
    ol: 'my-6 ml-6 list-decimal [&>li]:mt-2',
    olDepth: [
      'list-outside !list-decimal',
      'list-outside !list-[upper-roman]',
      'list-outside !list-[lower-roman]',
      'list-outside !list-[upper-alpha]',
      'list-outside !list-[lower-alpha]',
    ],
    ul: 'm-0 p-0 list-outside',
  },
  hashtag: 'text-content-presentation-badge-blue bg-background-presentation-badge-blue rounded-md px-1',
  text: {
    bold: 'font-bold',
    code: 'bg-background-presentation-form-base p-1 rounded-md',
    italic: 'italic',
    strikethrough: 'line-through',
    subscript: 'sub',
    superscript: 'sup',
    underline: 'underline',
    underlineStrikethrough: 'underline line-through',
  },
  image: 'relative inline-block user-select-none cursor-default editor-image',
  inlineImage:
    'relative inline-block user-select-none cursor-default inline-editor-image',
  keyword: 'text-content-presentation-badge-purple font-bold',
  code: 'font-mono text-sm block p-2 my-2 overflow-x-auto border border-border-system-global-secondary rounded-lg tab-size-2 relative',
  codeHighlight: {
    atrule: 'text-content-presentation-badge-purple',
    attr: 'text-content-presentation-badge-purple',
    boolean: 'text-content-presentation-badge-red',
    builtin: 'text-content-presentation-badge-green',
    cdata: 'text-content-system-global-secondary',
    char: 'text-content-presentation-badge-green',
    class: 'text-content-presentation-badge-rose',
    'class-name': 'text-content-presentation-badge-rose',
    comment: 'text-content-system-global-secondary',
    constant: 'text-content-presentation-badge-red',
    deleted: 'text-content-presentation-badge-red',
    doctype: 'text-content-system-global-secondary',
    entity: 'text-content-presentation-badge-orange',
    function: 'text-content-presentation-badge-rose',
    important: 'text-content-presentation-badge-yellow',
    inserted: 'text-content-presentation-badge-green',
    keyword: 'text-content-presentation-badge-purple',
    namespace: 'text-content-presentation-badge-yellow',
    number: 'text-content-presentation-badge-red',
    operator: 'text-content-presentation-badge-orange',
    prolog: 'text-content-system-global-secondary',
    property: 'text-content-presentation-badge-red',
    punctuation: 'text-content-system-global-secondary/70',
    regex: 'text-content-presentation-badge-yellow',
    selector: 'text-content-presentation-badge-green',
    string: 'text-content-presentation-badge-green',
    symbol: 'text-content-presentation-badge-red',
    tag: 'text-content-presentation-badge-red',
    url: 'text-content-presentation-badge-orange',
    variable: 'text-content-presentation-badge-yellow',
  },
  characterLimit: '!bg-background-presentation-state-negative-primary/50',
  table: 'EditorTheme__table w-fit overflow-scroll border-collapse',
  tableCell:
    'EditorTheme__tableCell w-24 relative border px-4 py-2 text-left [&[align=center]]:text-center [&[align=right]]:text-right',
  tableCellActionButton:
    'EditorTheme__tableCellActionButton bg-background-system-body-primary block border-0 rounded-2xl w-5 h-5 text-content-system-global-primary cursor-pointer',
  tableCellActionButtonContainer:
    'EditorTheme__tableCellActionButtonContainer block right-1 top-1.5 absolute z-10 w-5 h-5',
  tableCellEditing: 'EditorTheme__tableCellEditing rounded-sm shadow-sm',
  tableCellHeader:
    'EditorTheme__tableCellHeader bg-background-system-body-secondary border px-4 py-2 text-left font-bold [&[align=center]]:text-center [&[align=right]]:text-right',
  tableCellPrimarySelected:
    'EditorTheme__tableCellPrimarySelected border border-border-presentation-action-primary border-solid block h-[calc(100%-2px)] w-[calc(100%-2px)] absolute -left-[1px] -top-[1px] z-10 ',
  tableCellResizer:
    'EditorTheme__tableCellResizer absolute -right-1 h-full w-2 cursor-ew-resize z-10 top-0',
  tableCellSelected: 'EditorTheme__tableCellSelected bg-background-system-body-secondary',
  tableCellSortedIndicator:
    'EditorTheme__tableCellSortedIndicator block opacity-50 absolute bottom-0 left-0 w-full h-1 bg-background-system-body-secondary',
  tableResizeRuler:
    'EditorTheme__tableCellResizeRuler block absolute w-[1px] h-full bg-background-presentation-action-primary top-0',
  tableRowStriping:
    'EditorTheme__tableRowStriping m-0 border-t p-0 even:bg-background-system-body-secondary',
  tableSelected: 'EditorTheme__tableSelected ring-2 ring-border-presentation-state-focus ring-offset-2',
  tableSelection: 'EditorTheme__tableSelection bg-transparent',
  layoutItem: 'border border-dashed px-4 py-2',
  layoutContainer: 'grid gap-2.5 my-2.5 mx-0',
  autocomplete: 'text-content-system-global-secondary',
  blockCursor: '',
  embedBlock: {
    base: 'user-select-none',
    focus: 'ring-2 ring-border-presentation-state-focus ring-offset-2',
  },
  hr: 'p-0.5 border-none my-1 mx-0 cursor-pointer after:content-[""] after:block after:h-0.5 after:bg-background-system-body-secondary selected:ring-2 selected:ring-border-presentation-state-focus selected:ring-offset-2 selected:user-select-none',
  indent: '[--lexical-indent-base-value:40px]',
  mark: '',
  markOverlap: '',
}
